### ISSUE TITLE
강의계획서 조회 중 엔터를 눌러서 조회 가능하게 만들 수 있을까요?

### ISSUE THREAD

**Issue by mirusu400** [nbsp1221/klas-helper#10]
안녕하세요. 현재 본 확장 프로그램을 잘 쓰고있는 학생입니다.

현재 KLAS 홈페이지에서 강의계획서를 조회하기 위해선, 관련 정보를 입력하고 직접 `조회`버튼을 눌러서 조회를 해야 정상적으로 조회를 합니다.
확장 프로그램을 통해 조회를 누르는게 아닌, 단순히 엔터 버튼만 눌러도 조회가 가능하도록 기능 추가를 부탁드려도 될까요?

**Comment by nbsp1221** [comment]
이슈 감사합니다! 좋은 기능이네요. 추가했습니다~

**Comment by mirusu400** [comment]
방금 테스트해보고 잘 작동되는것을 확인했습니다. 감사합니다!

**Comment by romantickub** [comment]
> 했습니다테스트해보고잘작동되는것을확인했습니다 감사합니다!

Hi mirusu400 서버 파일이 필요합니다. you  
I want fils server you edit TA new
