### ISSUE TITLE
쿨타임 2분 제거 후 바로 강의를 시작할 때 문제

### ISSUE THREAD

**Issue by appano1** [nbsp1221/klas-helper#12]
환경: macOS(Catalina) - 버전 10.15.4, Chrome - 버전 81.0.4044.122(공식 빌드) (64비트)

![image](https://user-images.githubusercontent.com/36293619/80896802-404c2c00-8d2d-11ea-9a58-4ef441c70a0f.png)
위처럼 강의 진행률은 100%가 되지만, 학습시간이 강의를 들어도 1분에서 늘어나지 않습니다.

이는 부정한 방법으로 출석했다고 판단되어 추후 불이익이 발생할 수 있는 부분으로 보입니다.

**Comment by nbsp1221** [comment]
이슈 감사합니다! 혹시 강의를 다 보신 뒤에 강의를 끄지 않고 바로 다음 강의 보기를 눌러서 시청하셨나요? 그럴 경우 동시에 여러 콘텐츠 학습한 것으로 판단되어 문제가 생길 수 있습니다. 번거롭더라도 강의를 종료한 뒤에 다시 실행해 주시길 바랍니다.

**Comment by appano1** [comment]
klas spv/lis/lctre/viewer/LctreCntntsViewSpvPage.do 내부에 fnCmdClose() 라는 함수를 이용하면 강의를 종료할 수 있는데, 강의를 끄지 않더라도 이어서 강의를 누를 경우 해당 함수를 실행시켜 강의를 종료 시킨 뒤 열 수 있지 않을까요

**Comment by nbsp1221** [comment]
해당 이슈가 정말로 그 문제 때문에 생기는 것이 맞는지 잘 모르겠네요. 강의만 정상적으로 종료하면 저런 문제가 생기지 않나요? 원인이 이게 맞으면 자동으로 창이 꺼지도록 한 번 시도해 보겠습니다.

**Comment by appano1** [comment]
이게 출석과 연관이 있어서 제 계정으로 실험을 해보지를 못하겠네요..
나중에 다시 오류가 나온다면 다시 issue를 재오픈하겠습니다.

**Comment by nbsp1221** [comment]
지금 확인해 보니 2분 쿨타임 관련 코드에 ios 옵션이 추가되어 있었습니다. 그래서 이 코드를 포함해서 2분 쿨타임 제거 코드를 업데이트했어요. 환경이 macOS라고 하셔서 혹시 이와 관련이 있는 게 아닐까 싶습니다.
