### ISSUE TITLE
2분 쿨타임 초기화시 모든 강의의 학습 시간이 바뀌는 현상

### ISSUE THREAD

**Issue by appano1** [nbsp1221/klas-helper#13]
환경: macOS(Catalina) - 버전 10.15.4, Chrome - 버전 81.0.4044.122(공식 빌드) (64비트)

![image](https://user-images.githubusercontent.com/36293619/80912400-ad84af00-8d77-11ea-8c01-a3cb155c0e29.png)

2분 쿨타임 초기화시 이전에 학습시간을 채워 100%로 완료한 강의의 학습 시간이 전부 사라지는 현상이 있습니다.
다른 모든 강의도 마찬가지로 학습시간이 변경되었습니다.

**Comment by nbsp1221** [comment]
이 이슈는 #12 이슈와 서로 다른 문제인가요? 만약 같은 문제라면 이 이슈는 삭제하고 #12 이슈에 내용을 추가해 주세요.

2분 쿨타임을 초기화한다는 것은 쿨타임 제거 버튼을 누른다는 뜻 같고요. 쿨타임 제거 버튼을 누른 동시에 모든 과목의 학습 시간이 전부 사라지는 현상이 발생하는 건지 궁금하네요. 증상을 조금 더 자세히 설명해 주세요! 인정 시간이랑 실제 기록되는 학습 시간이 원래부터 다른 강의가 많았기 때문에 저 사진만으론 정확한 판단이 어렵네요.

**Comment by appano1** [comment]
다른 문제에요. 쿨타임 제거 버튼을 눌렀을 때 다른 모든 강의의 학습 시간이 줄어드는 현상입니다.
기존의 학습시간이 인정시간과 같았던 과목들의 학습시간이 조금씩 줄어들었습니다.

#12 이슈는 강의를 듣는 도중 강의의 2분 쿨타임을 없애고 다른 강의를 들었을 때 학습 시간은 1분인데 강의 진행률 %가 100%가 되면서 강의를 전부 들었다고 서버에서 판단해서 더 이상 학습 시간이 늘어나지 않는 경우입니다.

**Comment by appano1** [comment]
그런데 
> 정 시간이랑 실제 기록되는 학습 시간이 원래부터 다른 강의가 많았기 때문에 
해당 부분에 대해서 정확히 모르고 있어서, 학습 시간이 #12 이슈로 인해 생각하게 되면서 바뀌었다고 느낀 것일 수도 있겠다는 생각이 드네요..
다시 한번 #12 이슈가 생겼을 때, 전체적인 시간이 줄어드는지, 원래부터 달랐던 건지 정확히 판단을 해봐야할 것 같습니다...

**Comment by nbsp1221** [comment]
![제목 없음](https://user-images.githubusercontent.com/50603255/80917055-81792600-8d97-11ea-9ebc-30462cc0c05a.png)

그렇군요. 일단 제 케이스의 경우에도 원래부터 저렇게 인정 시간이랑 학습 시간이 다른 경우가 많았습니다. 해당 이슈는 아무래도 확실히 문제가 있어 보이지는 않는데 #12 이슈가 문제네요. 일단은 동시 컨텐츠 학습 때문에 발생한 것을 원인으로 보고 방지할 수 있도록 코드를 추가해 보겠습니다.
