### ISSUE TITLE
슬라이드로만 구성된 강의 다운로드

### ISSUE THREAD

**Issue by joyfuI** [nbsp1221/klas-helper#14]
[특정 강의](https://kwcommons.kw.ac.kr/em/5aa8e1354e1c9)가 영상을 다운받으면 검은 화면의 이상한 영상이 받아지길래 확인해보니까 영상은 오디오만 있고 따로 슬라이드 이미지를 보여주면서 그 위에 그림을 그리는 신기한 방식이더라고요.

https://kwcommons.kw.ac.kr/viewer/ssplayer/uniplayer_support/content.php?content_id=5aa8e1354e1c9
content_type 속성이 upf입니다.

이런 강의는 다운로드는 불가능할 것 같고 따로 구분을 해서 다운로드 버튼을 안띄우던지 오디오 다운로드 버튼으로 바꿔야할 것 같습니다.

-----

그리고 외부 스크립트를 불러오는 방식으로 바뀐 후부터는 스크립트 로딩이 됐다 안됐다 그러는 문제가 있습니다. ctrl+f5를 누르면 로드가 되서 캐시 문제로 추정했는데 이게 또 계속 반복해보니까 캐시 상태에서도 될 때가 있고 안 될 때가 있네요. 흠...
파이어폭스와 크롬에서 테스트해보니까 크롬은 아주 가끔 이 현상이 있고 파이어폭스는 자주 일어납니다.

**Comment by nbsp1221** [comment]
이슈 감사합니다! 저런 강의가 존재한다는 것은 이전부터 알고 있긴 했는데 content_type으로 구분이 기능했었군요. 오디오 다운로드 버튼 아이디어가 괜찮은 것 같네요. 이걸로 수정해 보겠습니다!

---

스크립트 적용이 안되는 문제도 이미 알고는 있었는데 크롬에선 거의 가끔만 일어나는 현상이라서 무시했는데 파이어폭스에서는 자주 일어난다니 문제가 있네요. 이 부분의 원인을 한 번 찾아봐야 할 것 같습니다. 스크립트가 로드는 되는데 실행이 안되는 것인지, 아니면 로드 자체가 안되는 것인지 궁금하네요.

**Comment by mirusu400** [comment]
새로운 이슈를 적으려다 동일한 Issue인듯 하여 답글 답니다.
https://kwcommons.kw.ac.kr/em/591d8a8ba9df6
위와 같은 영상 또한 이슈를 올려주신 분과 동일한 류의 영상입니다만, 이 영상은 교수님이 촬영하신 비디오와 강의 슬라이드 총 2개의 화면이 나옵니다.
이 때 확장 프로그램만을 이용해 다운로드를 시도하게 된다면 교수님이 촬영하신 비디오만 저장이 됩니다.

아마 이슈 제보하신 분이 다운로드를 시도하셨을때 검은 화면이 나오는 이유는 이 비디오가 저장이 안되있어서 나타나는 오류로 추정됩니다.

이러한 강의가 있을때 오디오만 다운받게 하기보단, 지금과 같이 다운이 가능하되 추가적인 기능을 이용해 슬라이드를 (가능하다면) 원본으로 다운받거나, 슬라이드 이미지 및 이미지가 바뀐 시간을 저장 가능하게끔 만드는것이 더 좋다고 생각합니다.

**Comment by joyfuI** [comment]
오 신기한 강의 형식이 많네요. (얘도 타입은 upf 군요.)
제 경우는 교수님이 위 형식의 강의에서 영상 대신 소리만 녹음하신거 같습니다.

-----

올려주신 강의 영상을 분석해보니
https://kwcommons.kw.ac.kr/contents/KW10000001/591d8a8ba9df6/contents/web_files/slide_list_(fd63770d-09f0-4903-8ba6-978f9679545d).xml
여기에서 슬라이드 이미지 정보를 얻을 수 있네요.

제가 klas-helper 개발자는 아니지만 아예 외부 프로그램을 제작하지 않는 이상, 이걸 유저 스크립트 선에서 다운로드 받는 건 불가능할 거 같습니다.

게다가 교수님이 중간중간 필기하는 부분은 얻을 수가 없네요. 이런 류는 그냥 직접 녹화하는 게 속편하겠습니다.

**Comment by nbsp1221** [comment]
제대로 된 영상이 표시되지 않는 강의에 대해서 '오디오 받기' 버튼으로 표시되도록 수정했습니다! 유저 스크립트를 업데이트해보시고 제대로 표시된다면 이슈를 닫아주세요~

**Comment by joyfuI** [comment]
오! 잘됩니다!
고생하셨습니다

**Comment by potados99** [comment]
안녕하세요. 타 학교 학생인데 `upf` 검색해보다가 여기까지 왔네요 ㅎㅎ    
강의 영상 보관하려고 했는데 그냥 슬라이드 저장하는 것에서 만족해야겠어요 ㅜ
