### ISSUE TITLE
그리스몽키 문제

### ISSUE THREAD

**Issue by joyfuI** [nbsp1221/klas-helper#17]
깜빡하고 생각못했는데 그리스몽키에서는 유저스크립트 내에서 웹페이지에 주입한 createElement 함수에 접근할 수가 없습니다.

그래서 다운로드 버튼 렌더링이 안됩니다.

**Comment by nbsp1221** [comment]
이슈 감사합니다! 확인을 하고 수정했어야 했는데 실수했네요. 제대로 작동되는 거 확인하시고 이슈 닫아주세요~

**Comment by joyfuI** [comment]
넵. 잘 됩니다. 감사합니다~
