### ISSUE TITLE
온라인 강의 다운로드 방식 수정

### ISSUE THREAD

**Issue by nbsp1221** [nbsp1221/klas-helper#19]
기존 방식의 경우 사용자가 '온라인 강의 컨텐츠 보기' 페이지에 접속하면 그 즉시 동영상의 정보를 서버에 요청해 모두 가져와서 다운로드 링크를 표시하는 방식이었습니다. 하지만 이 방법은 페이지에 접속할 때마다 강의의 개수만큼 서버에 요청을 보낸다는 문제가 있습니다. 최근에 사용자 수가 급증했던 경우도 있어서 서버에 부담이 되지 않을까 싶어 현재는 버튼을 눌러야만 다운로드 링크를 얻을 수 있도록 수정한 상태입니다.

---

다운로드 생성 버튼을 따로 눌러줄 필요가 없는 동시에 서버에도 많은 요청을 보내지 않을 수 있는 방법을 생각해 보았습니다만, 제 머리로는 좋은 방법이 생각이 나질 않네요.

더미 다운로드 버튼을 미리 생성해 놓고 사용자가 버튼을 클릭하는 순간 서버에 요청해 링크를 받아와서 다운하게 하는 방식을 고려해 보았지만, 강의마다 다운로드 버튼의 개수가 다를 수 있기에 이런 방법도 안될 것 같고요.

그냥 지금 상태처럼 다운로드 버튼을 생성하는 방식으로 유지하는 것이 최선인지, 더 좋은 방법은 없는지 궁금하네요. 혹시 좋은 아이디어가 있다면 댓글 남겨주시면 감사하겠습니다!

**Comment by mirusu400** [comment]
제가 웹 프로그래밍에 능통해서 이것이 가능한 방법인진 모르겠습니다만, 다운로드 버튼을 강의 목록에서 다운받는게 아닌 강의를 보는 창(https://klas.kw.ac.kr/spv/lis/lctre/viewer/LctreCntntsViewSpvPage.do )에서 다운로드하도록 하는것도 하나의 방법일 듯 싶습니다.

이 방법을 이용하면 사실상 인강을 창을 켜고 로딩될때 한번, 다운로드 할때 한번 총 두번만 요청하는 꼴이고, 이것도 가능한건지 모르겠지만, 정상적으로 볼때 영상을 넘겨주는 쿠키?를 가로채서 사용한다면 단 한번만의 요청으로 가능하지 않을까 생각해봅니다.

강의를 보는 창 윗부분에 진행률 / 학습시간 등을 표시하는 상태표시줄이 있는데, 이곳에 버튼을 추가로 매핑해 사용하면 다운로드게 열댓개가 넘어가지 않는 이상 외관상 문제도 생기지 않을 듯 싶네요.

강의 2분 쿨타임 제거와 함께 악의적으로 인강을 수집 또는 크롤링하기 위해 사용하는 유저를 제외하고는, 이 방법이 충분히 좋은 방법이라고 생각합니다.

**Comment by nbsp1221** [comment]
> 제가 웹 프로그래밍에 능통해서 이것이 가능한 방법인진 모르겠습니다만, 다운로드 버튼을 강의 목록에서 다운받는게 아닌 강의를 보는 창(https://klas.kw.ac.kr/spv/lis/lctre/viewer/LctreCntntsViewSpvPage.do )에서 다운로드하도록 하는것도 하나의 방법일 듯 싶습니다.
> 
> 이 방법을 이용하면 사실상 인강을 창을 켜고 로딩될때 한번, 다운로드 할때 한번 총 두번만 요청하는 꼴이고, 이것도 가능한건지 모르겠지만, 정상적으로 볼때 영상을 넘겨주는 쿠키?를 가로채서 사용한다면 단 한번만의 요청으로 가능하지 않을까 생각해봅니다.
> 
> 강의를 보는 창 윗부분에 진행률 / 학습시간 등을 표시하는 상태표시줄이 있는데, 이곳에 버튼을 추가로 매핑해 사용하면 다운로드게 열댓개가 넘어가지 않는 이상 외관상 문제도 생기지 않을 듯 싶네요.
> 
> 강의 2분 쿨타임 제거와 함께 악의적으로 인강을 수집 또는 크롤링하기 위해 사용하는 유저를 제외하고는, 이 방법이 충분히 좋은 방법이라고 생각합니다.

이것도 좋은 방법인 것 같습니다! 아이디어 감사합니다~ 한번 고려해 볼게요
