### ISSUE TITLE
분할된 온라인 강의 동영상 문제

### ISSUE THREAD

**Issue by joyfuI** [nbsp1221/klas-helper#2]
몇몇 온라인 강의 다운로드 시에 실제 강의보다 짧은 동영상이 다운로드 되는 문제를 발견하고 살펴보니까 일부 강의는 동영상이 분할되어 있었습니다.

예를 들어 [이 강의](https://kwcommons.kw.ac.kr/em/5e68a6eed3618)는 동영상 하단에 마우스 커서를 올리면 아래처럼 책갈피 같은 게 뜨는데요.

![이미지 1](https://user-images.githubusercontent.com/1342862/77036108-a5ec8f00-69f1-11ea-87c8-62f912c77c0e.png)

개발자 도구로 살펴보니 해당 지점부터 동영상 주소가 바뀝니다.

[https://kwcommons.kw.ac.kr/viewer/ssplayer/uniplayer_support/content.php?content_id=5e68a6eed3618](https://kwcommons.kw.ac.kr/viewer/ssplayer/uniplayer_support/content.php?content_id=5e68a6eed3618)
이 주소로 살펴보면 3개의 동영상 파일명을 반환하더라고요.
현재 스크립트 상에서는 3개 중 첫 번째만 다운로드 버튼을 생성하고 있습니다.

**Comment by nbsp1221** [comment]
버그 제보 감사합니다! 수정했으니 테스트 부탁드릴게요. 제 강의엔 분할된 강의가 없어서 테스트를 못해보네요 ㅠ

**Comment by joyfuI** [comment]
![이미지 1](https://user-images.githubusercontent.com/1342862/77065426-a05c6c80-6a24-11ea-8350-96b6a878f16b.png)

잘 작동합니다. 감사합니다ㅎㅎ
