### ISSUE TITLE
동영상 다운로드 문의

### ISSUE THREAD

**Issue by maple-maelin** [nbsp1221/klas-helper#23]
동영상을 다운 받을려고 하는데  동영상#2버튼을 눌렀는데, 보통은 강의화면이 다운로드 되는데, 강의화면 대신 강의를 녹화하시는 교수님 얼굴이 나타나서 이건 오류인지 아닌지 문의드리고 싶습니다.
<img width="817" alt="동영상 다운로드" src="https://user-images.githubusercontent.com/63298534/82337763-15e5b880-9a27-11ea-9b40-ad94d2f82c9d.PNG">

**Comment by nbsp1221** [comment]
오류가 아닙니다! 교수님이 강의 화면을 직접 녹화한 경우가 아니고, 영상처럼 보이지만 이미지에 그림을 그리는 형태(?)로 표현하는 학교 시스템을 이용하신 겁니다. 마치 PPT 슬라이드 화면에 펜으로 글씨는 쓰는 것처럼요. 목소리만 따로 녹음한 형태라고 볼 수 있겠네요. 이런 경우에는 아쉽지만 녹화 프로그램으로 직접 녹화하는 방법밖엔 없습니다.

참고로 저 다운로드 버튼 생성 기능은 곧 사라질 기능이니, 강의 화면에 있는 다운로드 기능을 사용해 주시기 바랍니다! 더 궁금하신 점이 있으면 여기에 댓글을 남겨주시고, 해결되셨으면 이슈를 닫아주세요!

**Comment by maple-maelin** [comment]
넵! 답변 감사합니다.
