### ISSUE TITLE
학습 기간이 얼마 남지 않은 강의를 따로 표시

### ISSUE THREAD

**Issue by nbsp1221** [nbsp1221/klas-helper#24]
> 온라인 강의를 덜 들었거나 듣지 않은 것이 있을경우 학습기간이 끝나기 2~3일전에 시간표같은곳에 표시되었으면 좋겠습니다

시간표에 추가되게 하는 것은 유저 스크립트의 한계상 어려울 것 같고, 현재 생각나는 방법으론 강의 종합 페이지나 온라인 강의 컨텐츠 보기 페이지에 따로 표시해서 알려주는 방법이 가장 좋을 것 같네요. 더 좋은 의견 있으면 댓글 남겨주세요!

**Comment by maple-maelin** [comment]
로그인하자마자 화면이 열리면 시간표랑 수강하는과목 목록이 뜨니까 수강기간이 끝나는  과목이름옆에 전구같은 아이콘이 깜빡이게 하는건 어떨까요?

**Comment by hyunsungyoo** [comment]
학습기간이 얼마 안남은 강의가 있으면 개인정보의 메일주소로 알림이 가능건 어떨까요?

**Comment by nugullpunch** [comment]
온라인 강의리스트를 참조하여  진도율이 100%가 아닐 때 과목 현황배너에서 주의표시같은것을 표시하는건 어떤가요?

**Comment by nbsp1221** [comment]
많은 분들이 의견을 남겨주셨네요. 감사합니다~

일단 유저 스크립트가 그렇게 대단한 기능은 아니고, 단순히 JavaScript를 실행하는 역할만 하기 때문에, 페이지 내부에 있는 정보만 이용할 수 있어요. 그래서 제가 생각하기엔 과목 이름 옆에 전구 같은 아이콘을 깜빡이게 한다거나, 이메일을 보내는 구현은 어려울 것 같아요.

제일 이상적인 구현이 로그인하자마자 보이는 창에 표시를 하는 것이 제일 좋겠지만, 그게 어려우니 강의 목록을 얻을 수 있는 `강의 종합` 페이지나 `온라인 강의 컨텐츠 보기` 페이지 중에서 마감이 얼마 남지 않은 강의를 상위에 따로 표시한다든지, 안내 문구로 알려주는 방식을 이용해야 하지 않을까 싶습니다.

> 온라인 강의리스트를 참조하여 진도율이 100%가 아닐 때 과목 현황배너에서 주의표시같은것을 표시하는건 어떤가요?

과목 현황 배너라면 어디를 말씀하시는 건가요? 이 부분도 마찬가지로 강의 리스트가 없는 페이지라면 구현이 힘들 것 같네요.

**Comment by ssahn0806** [comment]
axios.post 기능을 활용해서 각 과목별 과제제출페이지와 온라인 강의리스트 페이지를 참조하여,
전자의 경우에는 제출여부 그리고 expiredate와 현재날짜를 비교하여 카운트하고, 온라인 강의리스트의 경우에도 비슷한 방식으로 구현할 수 있지 않을까 생각해봅니다.

**Comment by nbsp1221** [comment]
> axios.post 기능을 활용해서 각 과목별 과제제출페이지와 온라인 강의리스트 페이지를 참조하여,
> 전자의 경우에는 제출여부 그리고 expiredate와 현재날짜를 비교하여 카운트하고, 온라인 강의리스트의 경우에도 비슷한 방식으로 구현할 수 있지 않을까 생각해봅니다.
> 
> 로그인 후 첫화면의 수강과목의 목록은 코드를 살펴보니 각 과목들에 대한 정보는 모두 가지고 있는 것 같습니다.

axios.post 방식이 있었군요. 메인 페이지에 과목에 대한 정보가 다 담겨있다면 이를 이용해서 충분히 구현이 가능할 것 같네요! 과제 같은 경우에는 일정에 과제 마감 순으로 따로 표시되기도 하니까 일단은 고려하지 않는다고 하고, 수강 과목 부분에 듣지 않은 온라인 강의가 있을 경우 경고 표시를 하는 식으로 만들면 될 것 같네요. 감사합니다 😄

**Comment by ssahn0806** [comment]
메인 페이지의 일정 아래부분으로 위치를 이동시키면 과제에 대한 부분과 함께 한눈에 볼 수 있을 것 같습니다!

**Comment by nbsp1221** [comment]
> 메인 페이지의 일정 아래부분으로 위치를 이동시키면 과제에 대한 부분과 함께 한눈에 볼 수 있을 것 같습니다!

로그인하자마자 바로 볼 수 있도록 일부러 최상단에 위치시킨 거긴 한데, 일정이랑 같이 보게 할 수 있는 것도 좋을 것 같네요!
