### ISSUE TITLE
수강과목 현황

### ISSUE THREAD

**Issue by kimziou77** [nbsp1221/klas-helper#27]
![1](https://user-images.githubusercontent.com/41179265/82769926-98300b80-9e71-11ea-9b67-631f90ee0235.png)

남아있는 과제들이 있음에도 불구하고 다음과 같은 화면이 나옵니다!

**Comment by ssahn0806** [comment]
저도 일부 과목에 대해 같은 현상이 발생합니다.

**Comment by nbsp1221** [comment]
헉.. 이건 정말 큰 문제인데요. 일단 이 방식이 온라인 강의 컨텐츠 목록에서 과제를 불러오는 거라서 온라인 강의 컨텐츠에 과제가 있나 확인 가능할까요? 그리고 과제가 어떤 형태(?)로 되어있는지도 알 수 있는지 궁금하네요. 일단 현재 상태로는 추가 제출 기한의 경우 표시되지 않는걸로 알고 있습니다.

**Comment by kimziou77** [comment]
![image](https://user-images.githubusercontent.com/41179265/82774995-56a75c80-9e81-11ea-9894-f515a82760d8.png)
온라인과제컨텐츠에는 나오지 않고
따로 과제게시판에 올라온 과제입니다!

**Comment by ssahn0806** [comment]
온라인 강의 컨텐츠 목록상에서는 교수님께서 과제에 설정한 주차에 영상강의가 없어서 따로 표기되지 않는 과제는 표시되지 않는 거군요.
윗분 말처럼 과제 제출 페이지의 스크립트에서 list의 indate,expiredate 속성을 활용하면 되지 않을까 싶습니다.
기한이 남아있지만 이미 제출했다면 submityn 속성을 활용해서  카운트 하지 않으면 될 것 같구요.

**Comment by nbsp1221** [comment]
axios 요청 줄인다고 온라인 강의 컨텐츠에서 한번에 긁어오는게 문제였군요.. 직접 과제 페이지에서 불러올 수 있도록 수정해야겠습니다. 이슈 감사합니다!

**Comment by nbsp1221** [comment]
일단 직접 과제 페이지에서 파싱할 수 있게 수정해 보았습니다! 해결돼셨으면 이슈를 닫아주세요~

**Comment by kimziou77** [comment]
해결되었습니다. 감사합니다
