### ISSUE TITLE
수강과목 현황

### ISSUE THREAD

**Issue by OctopusET** [nbsp1221/klas-helper#31]
![image](https://user-images.githubusercontent.com/18513799/83379387-5de8e000-a416-11ea-9936-5c83a2464051.png)
지난 번 이슈처럼 계속 이렇게 나옵니다. 수정되기 전에는 잘나왔는데 오히려 수정된후에 안나오네요.

사용환경:
Firefox(76.0.1) Windows10,Linux

**Comment by nbsp1221** [comment]
Firefox의 확장 프로그램은 무엇을 사용하셨나요? 혹시 윈도우 환경에서의 크롬에서 테스트를 해보실 수 있는지 궁금합니다.

**Comment by OctopusET** [comment]
윈도우환경에서 크롬에선 정상작동합니다.
확장프로그램은 여러가지 사용하나, 시크릿탭에서 tempermonkey만 허용했을때도 같은 결과가 나오며, 다른확장프로그램들을 따로 꺼도 동일하네요

**Comment by nbsp1221** [comment]
윈도우 환경에서는 정상 작동하는데, 리눅스 환경 firefox 브라우저에서는 tampermonkey를 사용함에도 불구하고 정상적으로 작동하지 않는다는거죠?

**Comment by OctopusET** [comment]
제가 전달을 잘못한것같습니다. 윈도우 환경 크롬은 정상작동하나
윈도우 환경 파이어폭스는 작동하지 않습니다.

**Comment by nbsp1221** [comment]
확인했습니다. 파이어폭스에서 작동하지 않는 문제가 있네요. 원인을 한번 찾아보겠습니다.

**Comment by OctopusET** [comment]
정상 작동합니다감사합니다
