### ISSUE TITLE
수강 과목 현황에 하이퍼링크 추가

### ISSUE THREAD

**Issue by mirusu400** [nbsp1221/klas-helper#32]
![chrome_KXMssKfErI](https://user-images.githubusercontent.com/25397908/83644827-aa861400-a5ec-11ea-9560-457197be3df1.png)

안녕하세요.

최근에 생긴 기능중에 위와같이 남은 강의 및 과제 수를 klas 메인 화면에 나타내는 `수강 과목 현황`기능이 추가된것을 알았습니다.

하지만 위 기능은 단순히 보여주기만 하는 기능이라서 직접 강의시청 / 과제제출을 할려면 일일히 수동으로 들어가야 하는 문제점이 있는데요,

일반 텍스트가 아닌 각 항목에 과목의 온라인 강의컨텐츠 란 / 과제제출 란을 `하이퍼링크`해 클릭하면 바로 강의시청 및 과제제출이 가능하도록 수정하면 더 편할듯합니다.

**Comment by nbsp1221** [comment]
이슈 감사합니다~ 추가해 보도록 하겠습니다. 😀

**Comment by maple-maelin** [comment]
저 위에 사진에서 과목 (예를 들어 공학수학1을 클릭하면)을 클릭해서 온라인강좌로 바로 넘어가게 한다는 거죠!??

**Comment by mirusu400** [comment]
@maple-maelin 네 맞습니다.
예를 들어 굵은 글씨로 표시된 `공학수학`을 클릭하면 공학수학의 `강의종합`으로 이동하고,
공학수학 옆의 `~일 후 마감인 강의가 ~개 있습니다` 를 클릭하면 공학수학의 `온라인 강의컨텐츠 보기`로 이동하고,
마찬가지로 옆의 `~일 후 마감인 과제가 ~개 있습니다`를 클릭하면 공학수학의 `과제제출`로 이동하는것이 좋아보입니다.

**Comment by ssahn0806** [comment]
관련된 문의라 이곳에 올립니다. 현재 과제 현황의 경우에는 제출하지 않은 과제 중 제출기한이 가장 임박한 대상만 보여주는데, 옆에 남아 있는 과제의 총 갯수도 함께 표현해주면 좋을 것 같습니다.

**Comment by nbsp1221** [comment]
@mirusu400, @ssahn0806 

수강 과목 현황에 하이퍼링크를 추가하고 남은 총 강의의 개수와 과제의 개수를 볼 수 있도록 수정했습니다! 확인해보시고 문제가 없으시면 이슈를 닫아주세요~

**Comment by mirusu400** [comment]
@nbsp1221 
확인결과 잘 되는듯 하여 이슈를 닫겠습니다.
항상 감사합니다!
