### ISSUE TITLE
On Edge browser, klas-helper doesn't work 

### ISSUE THREAD

**Issue by iyu88** [nbsp1221/klas-helper#35]
On web browser 'Edge' which MS launched out, 

Somehow I can not use this program.

As far as I know, Chrome Extensions should be compatible with Edge as well,

but klas-helper doesn't apply to it.

I don't know exactly whether that is a problem of TamperMonkey or not, 

just wanna know people have same issue like I mentioned above.

**Comment by OctopusET** [comment]
Is your edge browser is newer version(chromium based) or legacy version(Spartan)?

**Comment by joyfuI** [comment]
When I tested it, it works well after installing TamperMonkey.
(Legacy Edge)

**Comment by iyu88** [comment]
It's chromium based one.

Would you test on it, and leave comments?

**Comment by nbsp1221** [comment]
It works well. I tested it in `Version 83.0.478.54 (Official build) (64-bit)`.

**Comment by mirusu400** [comment]
It also works on my environment, please provide detailed information about your environment. If we cannot implement bugs on our environment, we'll close this issue.
