### ISSUE TITLE
How about add 'To the Top' Button on user's display

### ISSUE THREAD

**Issue by iyu88** [nbsp1221/klas-helper#36]
As everyone knows, there is a 'back to top' Button 

on the very footer of original KLAS.

And I want it to follow user's display.

Because now the scroll is too long to go all the way up and 

sometimes I want to right go to the global menu in the middle of page.

So by fixing it on the lower right side of browser it's gonna be more useful than now.

**Comment by joyfuI** [comment]
I think that's a good idea.

-----

```js
$('.btnup').css({
	position: "fixed",
	right: "30px",
	bottom: "30px"
});
```
적당히 요런 코드를 window.onload 안에 넣으면 될 거 같습니다.

**Comment by nbsp1221** [comment]
Thanks to @joyfuI for the solution! I've updated it. Please check it and close the issue.
