### ISSUE TITLE
비디오 다운로드 관련 문의

### ISSUE THREAD

**Issue by ssahn0806** [nbsp1221/klas-helper#4]
starting 프로퍼티를 가지고 있는 list의 항목임에도 불구하고, 다운로드 버튼이 생기지 않는 경우가 종종 있습니다. 이 경우에는 영상의 제작자가 해당 영상을 지운경우에 해당하는 것인가요? 보기를 통해서는 정상적으로 재생이 가능하긴 합니다만.. nbsp님 덕분에 저도 자바스크립트를 조금씩 알아가서 도움이 많이 됩니다 ㅎ

**Comment by nbsp1221** [comment]
학교 시스템을 통해서 올린 인강이 아닌 경우 (예: 유튜브 등) 다운로드가 안될 수 있습니다. F12 개발자 도구로 들어갔을 때 혹시 오류가 뜨지 않나요? [KLAS Helper Error] 항목으로 오류가 뜨는 내용이 있으면 알려주세요. 아무런 오류가 뜨지 않는다면, starting 값을 직접 알려주시면 좋을 것 같아요.

**Comment by seungsuAhn** [comment]
오류는 따로 발생하지 않고, 버젼업데이트 전에는 다운로드가 되었던 항목입니다. "https://kwcommons.kw.ac.kr/em/5e67421dbd32"

**Comment by nbsp1221** [comment]
혹시 다운로드 버튼이 일부 동영상만 안 생기는 건가요, 아니면 모든 동영상에서 안 생기는 건가요?

**Comment by ssahn0806** [comment]
일부 교과목에 대한 모든 동영상에서 생성되지 않고 있어요.

**Comment by nbsp1221** [comment]
일단 수정해 봤는데 업데이트 후 체크 부탁드릴게요. 그리고 KLAS 오류가 아니더라도 아무거나 스크립트 오류가 나는게 있으면 알려주세요.

**Comment by ssahn0806** [comment]
제 기준으로 수강 과목 중 2과목이 위 현상이 발생했는데요, 이 중 한 과목은  default.htm 이었던 강좌가 업로더에 의해 모두 starting이 설정되고 나니 다운로드 버튼이 생겼습니다. 나머지 한과목은 현재 올라온 영상 중 default.htm인 항목이 남아 있는 상황이고, 다운로드 버튼은 없습니다. 좀 더 지켜보고 경과를 말씀드릴게요!

**Comment by nbsp1221** [comment]
default.htm인 상황에서도 다운로드 버튼은 생기게 해뒀는데 좀 이상하네요. 모든 동영상에에서 생성되지 않는 현상은 해결되셨나요?

**Comment by ssahn0806** [comment]
네네 그건 해결되었습니당. 현재 다운로드 버튼이 뜨지 않는 과목은, 수강가능일자가 지나고 나서 테스트 한번 또 해볼게요.

**Comment by ssahn0806** [comment]
수강가능일이 되고 나니 정상적으로 모두 해결되었습니다.
