### ISSUE TITLE
Video player keyboard short cuts

### ISSUE THREAD

**Issue by iyu88** [nbsp1221/klas-helper#40]
Space bar > Pause/ Play the video
Backspace , p > Previous presentation page
n > Next presentation page
Right and Left arrow keys > Move forward or backward by 10 sec 
Up and Down arrow keys > Raise or lower volume by 10%
x , c > Decrease or increase play speed by 0.2
m > Mute/ Unmute video volume
Enter , f > Enter or exit fullscreen
esc > Exit fullscreen

These are usable keyboard short cuts on video class.

It would be better to put every key information above on the page, 

but I think there isn't enough space for all of them.

So I recommend to add info at least about <p,n> and <x,c>

which are quite useful but relatively not well known.

In my opinion, right side of 'Hiding Lecture' button is proper place for them.

**Comment by nugullpunch** [comment]
저는 'z' : 1.0배속 재생도 자주 쓰고 있습니다.
단축키를 모른다면 마우스로 배속 조정 혹은 영상시각 이동을 하고 있을텐데
단축키를 알 수 있다면 사람들도 단축키를 유용하게 쓸 것 같습니다.

**Comment by nbsp1221** [comment]
I have added a legend of keyboard shortcuts in the online lecture viewer page. Thank you for your good idea! Please check it and close this issue.

![Untitled](https://user-images.githubusercontent.com/50603255/86587299-4d52f900-bfc4-11ea-80f6-d477054b31c9.png)
