### ISSUE TITLE
팀 프로젝트 과제 표시

### ISSUE THREAD

**Issue by nugullpunch** [nbsp1221/klas-helper#43]
수강 과목 현황 과제 목록에서 팀프로젝트 과제의 남은 기간도 참조하여 표시가 되면 좋겠습니다.

**Comment by nbsp1221** [comment]
이슈 감사합니다. 팀 프로젝트의 경우 저한테 데이터가 없어서 확인해보기가 어렵네요. #27 이슈처럼 개발에 필요한 정보를 제공해 주실 수 있는 분이 있으면 댓글로 남겨주세요!

**Comment by nugullpunch** [comment]
![팀프 스샷](https://user-images.githubusercontent.com/64082500/84599337-4137b800-aeac-11ea-8ab9-b18029cd0e4c.JPG)
이렇게 나옵니다.
