### ISSUE TITLE
강의 동영상이 재생이 안되고 사이트 주소가 다르다고 뜨는 오류

### ISSUE THREAD

**Issue by pangpangyc** [nbsp1221/klas-helper#53]
헬퍼를 깔고 강의를 재생했는데 강의 동영상이 재생이 안되고 사이트 주소가 다르다고 뜨네요. 그래서 tampermonkey 를 지우고 스크립트를 지웠는데도 강의재생이 안됩니다. 크롬뿐만 아니라 다른 브라우저들도 안되네요. 적어도 깔기 전에는 됐었는데 어떻게 해야되나요???

**Comment by nbsp1221** [comment]
아마 이건 교수님이 잘못 올리셨거나 강의를 삭제했을 가능성이 큽니다!
