### ISSUE TITLE
다운로드 버튼을 눌러 새로운 팝업창에서 영상을 재생할때

### ISSUE THREAD

**Issue by ssahn0806** [nbsp1221/klas-helper#6]
방향키 입력을 통해 컨트롤 할 수 있었으면 좋겠습니다..

물론, 다운로드를 받아 플레이어에서 재생하면 위처럼 되긴 하네요.

**Comment by nbsp1221** [comment]
해당 부분은 동영상 파일(mp4 등)을 브라우저에서 직접 실행하는 것으로 브라우저의 기능 문제입니다. 원래는 영상 다운로드 버튼을 누르면 바로 동영상 파일로 다운되는 것이 맞지만, 브라우저마다 이러한 차이가 생기는 것 같이 보이네요.

다운로드 기능은 동영상 파일을 다운받을 목적으로 만든 것이기 때문에 웹 브라우저로 동영상을 시청하는 것은 원래의 정상적인 방법인 학교 인강을 이용해 주시면 감사하겠습니다. (사실 그 부분을 컨트롤하는 게 가능할지 의문이기도 하고, 가능하다고 쳐도 원래 제 프로그램의 용도를 많이 벗어나는 것 같아요.)

**Comment by ssahn0806** [comment]
브라우저의 문제였군요. 답변 감사드립니다
