### ISSUE TITLE
klas darkmode기능 제안

### ISSUE THREAD

**Issue by KyuhcH** [nbsp1221/klas-helper#79]
klas에서 dark mode로 전환할 수 있는 기능이 있으면 좋을 것 같습니다.

**Comment by mirusu400** [comment]
이슈 감사합니다.

![image](https://user-images.githubusercontent.com/25397908/141248608-45da7975-21aa-4505-bfda-4c8373b9e930.png)

우선 이 유저스크립트가 모든 페이지가 로드된 뒤에 동적으로 로드되는 방식이라서, 커스텀 CSS를 적용하는게 애매한 상황입니다. 추후 확장 프로그램으로 넘어가게 되면 다크모드나 사용자가 만든 css를 적용할수 있게끔 만들어볼 예정입니다.

수고하세요!

**Comment by mirusu400** [comment]
[Klas helper 확장 프로그램](https://github.com/mirusu400/klas-helper-extension) 에 다크모드를 추가했습니다.
