### ISSUE TITLE
강의동영상 다운로드 미작동 (파이어폭스)

### ISSUE THREAD

**Issue by joyfuI** [nbsp1221/klas-helper#9]
파이어폭스 사용 중입니다.

어느 날부터 갑자기 강의동영상 다운로드 버튼이 사라져서 확인해봤는데 1.6.1 이후부터 안 되더라구요.
바뀐 부분 하나하나 체크해서 원인을 찾았습니다.

https://github.com/nbsp1221/klas-helper/commit/719e9a7dea49962dff2eaaba7dbb411b3853b65d#diff-0ad84f775b5042ff57b2cbb9869ed821L482-L484

```javascript
				document.querySelectorAll('.btn-download').forEach(function (item) {
					item.style.display = 'none';
				});
```

<center>↓</center>

```javascript
				$('.btn-download').hide();
```

이 부분이 바뀌고부터 안 됩니다.
해당 변경사항만 원래대로 되돌리니까 다시 버튼이 잘 뜨네요.

제이쿼리냐 아니냐의 차이밖에 없는데 이게 왜 파이어폭스에서만 문제를 일으키는지 모르겠습니다;; 음...

**Comment by nbsp1221** [comment]
이슈 감사합니다! 아무래도 greasemonkey의 샌드박스 요소로 인해 jQuery에 접근을 못하는게 아닐까 싶네요. 버그 수정 후 greasemonkey에서 정상 동작하는 것을 확인하였습니다.
